
let arrobj=[
    {
       name:'Anshu',
       email:'anshu@gamil.com',
       phone:'7978985576',
       no_of_times_shopped:5,
       purchase_history:[
        {
           date_of_purchase:'01/07/2022',
           item_purchased:[
            {
                product_name:'mobile',
                product_price:50000
            },
            {
                product_name:'laptop',
                product_price:750000
            },
           ] 
        },
        {
            date_of_purchase:'15/06/2022',
            item_purchased:[
                {
                    product_name:'mixer',
                    product_price:8000
                },
            ]
        },
        {
            date_of_purchase:'1/06/2022',
            item_purchased:[
                {
                    product_name:'fan',
                    product_price:7000
                },
                {
                    product_name:'ac',
                    product_price:50000
                },
            ]
        },
       ]
    },
    
    {
        name:'nimisha',
        email:'nimi@gamil.com',
        phone:'7978985576',
        no_of_times_shopped:4,
        purchase_history:[
            {
                date_of_purchase:'01/07/2022',
                item_purchased:[
                    {
                        product_name:'mobile',
                        product_price:50000
                    },
                    {
                        product_name:'laptop',
                        product_price:750000
                    },
                ] 
            },
            {
                date_of_purchase:'15/06/2022',
                item_purchased:[
                    {
                        product_name:'mixer',
                        product_price:8000
                    },
                ]
            },
            {
                date_of_purchase:'1/06/2022',
                item_purchased:[
                    {
                        product_name:'fan',
                        product_price:1000
                    },
                    
                ]
            }
        ]
    },
        
    {
        name:'vivaan',
        email:'vivaan@gamil.com',
        phone:'7978985576',
        no_of_times_shopped:6,
        purchase_history:[
                {
                   date_of_purchase:'01/07/2022',
                   item_purchased:[
                    {
                        product_name:'mobile',
                        product_price:50000
                    },
                    {
                        product_name:'laptop',
                        product_price:750000
                    },
                   ] 
                },
                {
                    date_of_purchase:'15/06/2022',
                    item_purchased:[
                        {
                            product_name:'mixer',
                            product_price:8000
                        },
                    ]
                },
                {
                    date_of_purchase:'1/06/2022',
                    item_purchased:[
                        {
                            product_name:'fan',
                            product_price:7000
                        },
                        {
                            product_name:'ac',
                            product_price:50000
                        },
                    ]
                },
                {
                    date_of_purchase:'15/05/2022',
                    item_purchased:[
                        {
                            product_name:'tv',
                            product_price:80000
                        },
                    ]
                }
        ]
    },
    {
        name:'priyanka',
        email:'priyanka@gamil.com',
        phone:'7978985576',
        no_of_times_shopped:3,
        purchase_history:[
            {
                date_of_purchase:'01/07/2022',
                item_purchased:[
                    {
                        product_name:'mobile',
                        product_price:50000
                    },
                    {
                        product_name:'laptop',
                        product_price:750000
                    },
                ] 
            },
            {
                date_of_purchase:'15/06/2022',
                item_purchased:[
                    {
                        product_name:'mixer',
                        product_price:8000
                    },
                ]
            }
            
        ]
    },
    {
        name:'sonal',
        email:'sonal@gamil.com',
        phone:'7978985576',
        no_of_times_shopped:5,
        purchase_history:[
            {
                date_of_purchase:'01/07/2022',
                item_purchased:[
                    {
                        product_name:'mobile',
                        product_price:50000
                    },
                    {
                        product_name:'laptop',
                        product_price:750000
                    },
            ] 
            },
            {
                date_of_purchase:'15/06/2022',
                item_purchased:[
                    {
                        product_name:'mixer',
                        product_price:8000
                    },
                ]
            },
            {
                date_of_purchase:'1/06/2022',
                item_purchased:[
                    {
                        product_name:'fan',
                        product_price:7000
                    },
                    {
                        product_name:'ac',
                        product_price:50000
                    },
                ]
            },
        ]
    }
]

arrobj.forEach((value,index) => {
    let{name,email,phone,purchase_history}= value;
    console.log(name,email,phone,purchase_history[0]);

})

let filteredArr =arrobj.filter(item=>(item.no_of_times_shopped >= 5))
console.log(filteredArr);
let sum=0;
for(let i=0 ; i<arrobj.length;i++){
    for(let j=0;j<arrobj[i].purchase_history.length;j++){
        for(let k=0;k<arrobj[i].purchase_history[j].item_purchased.length;k++){
            sum=sum+arrobj[i].purchase_history[j].item_purchased[k].product_price
        }
    }
    console.log(`${arrobj[i].name} - ${sum}`);
    sum=0;
}
